function out = model
%
% WaterHammer_reservoir_numericmodel.m
%
% Model exported on Jun 18 2026, 15:29 by COMSOL 6.0.0.312.

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.modelPath('E:\Comsol_Runs\WaterHammer\ok\github');

model.label('WaterHammer_reservoir_numericmodel_v6_cylindrical_friction_v3_1_ok_comp_production_dt_changed_ok_volume_ok.mph');

model.param.set('density', '700[kg/m^3]');
model.param.set('dynamic_viscosity', '0.6e-3[Pa*s]');
model.param.set('speed_of_sound', '1000[m/s]');
model.param.set('comp_fluid', '2.18e-9[1/Pa]');
model.param.set('E', '210[GPa]*1e20', 'Pipe Young''s modulus');
model.param.set('porosity_pm', '0.25');
model.param.set('permeability_pm', '4.93e-14[m^2]');
model.param.set('friction_factor', '0.02');
model.param.set('L', '500[m]', 'Pipe length');
model.param.set('pipe_R', '7.42[cm]/2', 'Pipe inner radius');
model.param.set('w', '8[mm]*1e20', 'Pipe wall thickness');
model.param.set('Q0', '0.3[kg/s]/700[kg/m^3]', 'Initial flow rate');
model.param.set('u0', 'Q0/(pipe_R^2*pi)', 'Initial velocity');
model.param.set('porous_domain_radius', '15.06[m]');
model.param.set('porous_domain_thickness', '12[m]');
model.param.set('rw', '0.1[m]', 'porousmedia well radius');
model.param.set('p0', '100[bar]', 'Initial pressure');
model.param.set('Courant_number', '0.1');
model.param.set('N', '50', 'Number of mesh points');
model.param.set('pressure_reservoir_boundary', '138.006e5[Pa]');
model.param.set('dt_out', 'L/speed_of_sound/10', 'Time step according to CFL');
model.param.set('dt_max', 'Courant_number*L/N/speed_of_sound');

model.component.create('comp1', true);

model.component('comp1').geom.create('geom1', 3);

model.result.table.create('evl3', 'Table');
model.result.table.create('tbl1', 'Table');
model.result.table.create('tbl2', 'Table');
model.result.table.create('tbl3', 'Table');
model.result.table.create('tbl4', 'Table');
model.result.table.create('tbl5', 'Table');
model.result.table.create('tbl6', 'Table');
model.result.table.create('tbl7', 'Table');
model.result.evaluationGroup.create('eg1', 'EvaluationGroup');
model.result.evaluationGroup('eg1').create('pev1', 'EvalPoint');

model.component('comp1').func.create('rm1', 'Ramp');
model.component('comp1').func.create('step1', 'Step');
model.component('comp1').func('rm1').set('location', '0.05/(1e-2)');
model.component('comp1').func('rm1').set('cutoffactive', true);
model.component('comp1').func('step1').set('from', 1);
model.component('comp1').func('step1').set('to', 0);
model.component('comp1').func('step1').set('smoothactive', false);

model.component('comp1').mesh.create('mesh1');

model.component('comp1').geom('geom1').create('pol1', 'Polygon');
model.component('comp1').geom('geom1').feature('pol1').set('source', 'table');
model.component('comp1').geom('geom1').feature('pol1').set('table', {'0' '0' '0'; '0' '0' '-L'});
model.component('comp1').geom('geom1').create('blk1', 'Block');
model.component('comp1').geom('geom1').feature('blk1').set('pos', {'0' '0' '-L-porous_domain_thickness'});
model.component('comp1').geom('geom1').feature('blk1').set('size', {'porous_domain_radius' 'porous_domain_radius' 'porous_domain_thickness'});
model.component('comp1').geom('geom1').create('cyl1', 'Cylinder');
model.component('comp1').geom('geom1').feature('cyl1').set('pos', {'0' '0' '-L-porous_domain_thickness'});
model.component('comp1').geom('geom1').feature('cyl1').set('r', 'porous_domain_radius');
model.component('comp1').geom('geom1').feature('cyl1').set('h', 'porous_domain_thickness');
model.component('comp1').geom('geom1').create('cyl2', 'Cylinder');
model.component('comp1').geom('geom1').feature('cyl2').set('pos', {'0' '0' '-L-porous_domain_thickness'});
model.component('comp1').geom('geom1').feature('cyl2').set('r', 'rw');
model.component('comp1').geom('geom1').feature('cyl2').set('h', 'porous_domain_thickness');
model.component('comp1').geom('geom1').create('uni1', 'Union');
model.component('comp1').geom('geom1').feature('uni1').selection('input').set({'cyl1' 'cyl2'});
model.component('comp1').geom('geom1').create('dif1', 'Difference');
model.component('comp1').geom('geom1').feature('dif1').active(false);
model.component('comp1').geom('geom1').feature('dif1').selection('input').set({});
model.component('comp1').geom('geom1').feature('dif1').selection('input2').set({});
model.component('comp1').geom('geom1').create('int1', 'Intersection');
model.component('comp1').geom('geom1').feature('int1').selection('input').set({'blk1' 'uni1'});
model.component('comp1').geom('geom1').run;
model.component('comp1').geom('geom1').run('fin');

model.view.create('view3', 3);

model.component('comp1').material.create('mat1', 'Common');
model.component('comp1').material.create('pmat1', 'PorousMedia');
model.component('comp1').material('mat1').selection.geom('geom1', 1);
model.component('comp1').material('mat1').selection.all;
model.component('comp1').material('mat1').propertyGroup('def').func.create('eta', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func.create('Cp', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func.create('rho', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func.create('k', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func.create('cs', 'Interpolation');
model.component('comp1').material('mat1').propertyGroup('def').func.create('an1', 'Analytic');
model.component('comp1').material('mat1').propertyGroup('def').func.create('an2', 'Analytic');
model.component('comp1').material('mat1').propertyGroup('def').func.create('an3', 'Analytic');
model.component('comp1').material('pmat1').selection.set([1 2]);
model.component('comp1').material('pmat1').feature.create('fluid1', 'Fluid', 'comp1');

model.component('comp1').cpl.create('genext1', 'GeneralExtrusion');
model.component('comp1').cpl.create('genext2', 'GeneralExtrusion');
model.component('comp1').cpl('genext1').selection.set([1 2]);
model.component('comp1').cpl('genext2').selection.geom('geom1', 1);
model.component('comp1').cpl('genext2').selection.set([4]);

model.component('comp1').physics.create('dl2', 'PorousMediaFlowDarcy', 'geom1');
model.component('comp1').physics('dl2').identifier('dl2');
model.component('comp1').physics('dl2').field('pressure').field('p3');
model.component('comp1').physics('dl2').create('pr1', 'Pressure', 2);
model.component('comp1').physics('dl2').feature('pr1').selection.set([9]);
model.component('comp1').physics('dl2').create('ms1', 'MassSource', 3);
model.component('comp1').physics('dl2').feature('ms1').selection.set([1]);
model.component('comp1').physics.create('pfl', 'FlowInPipes', 'geom1');
model.component('comp1').physics('pfl').field('velocity').field('u2');
model.component('comp1').physics('pfl').field('pressure').field('p4');
model.component('comp1').physics('pfl').selection.set([4]);
model.component('comp1').physics('pfl').create('vf1', 'VolumeForce', 1);
model.component('comp1').physics('pfl').feature('vf1').selection.set([4]);
model.component('comp1').physics('pfl').create('out1', 'Outlet', 0);
model.component('comp1').physics('pfl').feature('out1').selection.set([3]);
model.component('comp1').physics.create('dl', 'PorousMediaFlowDarcy', 'geom1');
model.component('comp1').physics('dl').field('pressure').field('p2');
model.component('comp1').physics('dl').create('pr1', 'Pressure', 2);
model.component('comp1').physics('dl').feature('pr1').selection.set([9]);
model.component('comp1').physics('dl').create('ms1', 'MassSource', 3);
model.component('comp1').physics('dl').feature('ms1').selection.set([1]);
model.component('comp1').physics.create('whtd', 'WaterHammer', 'geom1');
model.component('comp1').physics('whtd').selection.set([4]);
model.component('comp1').physics('whtd').create('pres1', 'Pressure', 0);
model.component('comp1').physics('whtd').feature('pres1').selection.set([2]);
model.component('comp1').physics('whtd').create('source1', 'Source', 0);
model.component('comp1').physics('whtd').feature('source1').selection.set([3]);
model.component('comp1').physics('whtd').create('vf1', 'VolumeForce', 1);
model.component('comp1').physics('whtd').feature('vf1').selection.set([4]);

model.component('comp1').mesh('mesh1').create('ftet1', 'FreeTet');
model.component('comp1').mesh('mesh1').feature('ftet1').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftet1').create('dis1', 'Distribution');
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').selection.geom('geom1', 3);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').selection.set([1]);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('dis1').selection.set([4]);

model.component('comp1').probe.create('point1', 'Point');
model.component('comp1').probe.create('dom1', 'Domain');
model.component('comp1').probe.create('dom2', 'Domain');
model.component('comp1').probe('point1').selection.set([2]);
model.component('comp1').probe('dom1').selection.set([1]);
model.component('comp1').probe('dom2').selection.set([1]);

model.result.table('evl3').label('Evaluation 3D');
model.result.table('evl3').comments('Interactive 3D values');
model.result.table('tbl1').label('Probe Table 1');
model.result.table('tbl3').label('Table 3');

model.component('comp1').view('view1').set('transparency', true);

model.component('comp1').material('mat1').label('Water, liquid');
model.component('comp1').material('mat1').set('family', 'water');
model.component('comp1').material('mat1').propertyGroup('def').func('eta').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('def').func('eta').set('pieces', {'273.15' '413.15' '1.3799566804-0.021224019151*T^1+1.3604562827E-4*T^2-4.6454090319E-7*T^3+8.9042735735E-10*T^4-9.0790692686E-13*T^5+3.8457331488E-16*T^6'; '413.15' '553.75' '0.00401235783-2.10746715E-5*T^1+3.85772275E-8*T^2-2.39730284E-11*T^3'});
model.component('comp1').material('mat1').propertyGroup('def').func('eta').set('argunit', 'K');
model.component('comp1').material('mat1').propertyGroup('def').func('eta').set('fununit', 'Pa*s');
model.component('comp1').material('mat1').propertyGroup('def').func('Cp').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('def').func('Cp').set('pieces', {'273.15' '553.75' '12010.1471-80.4072879*T^1+0.309866854*T^2-5.38186884E-4*T^3+3.62536437E-7*T^4'});
model.component('comp1').material('mat1').propertyGroup('def').func('Cp').set('argunit', 'K');
model.component('comp1').material('mat1').propertyGroup('def').func('Cp').set('fununit', 'J/(kg*K)');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('smooth', 'contd1');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('pieces', {'273.15' '293.15' '0.000063092789034*T^3-0.060367639882855*T^2+18.9229382407066*T-950.704055329848'; '293.15' '373.15' '0.000010335053319*T^3-0.013395065634452*T^2+4.969288832655160*T+432.257114008512'});
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('argunit', 'K');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('fununit', 'kg/m^3');
model.component('comp1').material('mat1').propertyGroup('def').func('k').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('def').func('k').set('pieces', {'273.15' '553.75' '-0.869083936+0.00894880345*T^1-1.58366345E-5*T^2+7.97543259E-9*T^3'});
model.component('comp1').material('mat1').propertyGroup('def').func('k').set('argunit', 'K');
model.component('comp1').material('mat1').propertyGroup('def').func('k').set('fununit', 'W/(m*K)');
model.component('comp1').material('mat1').propertyGroup('def').func('cs').set('table', {'273' '1403';  ...
'278' '1427';  ...
'283' '1447';  ...
'293' '1481';  ...
'303' '1507';  ...
'313' '1526';  ...
'323' '1541';  ...
'333' '1552';  ...
'343' '1555';  ...
'353' '1555';  ...
'363' '1550';  ...
'373' '1543'});
model.component('comp1').material('mat1').propertyGroup('def').func('cs').set('interp', 'piecewisecubic');
model.component('comp1').material('mat1').propertyGroup('def').func('cs').set('fununit', {'m/s'});
model.component('comp1').material('mat1').propertyGroup('def').func('cs').set('argunit', {'K'});
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('funcname', 'alpha_p');
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('expr', '-1/rho(T)*d(rho(T),T)');
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('args', {'T'});
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('fununit', '1/K');
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('argunit', {'K'});
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('plotargs', {'T' '273.15' '373.15'});
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('funcname', 'gamma_w');
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('expr', '1+(T/Cp(T))*(alpha_p(T)*cs(T))^2');
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('args', {'T'});
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('fununit', '1');
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('argunit', {'K'});
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('plotargs', {'T' '273.15' '373.15'});
model.component('comp1').material('mat1').propertyGroup('def').func('an3').set('funcname', 'muB');
model.component('comp1').material('mat1').propertyGroup('def').func('an3').set('expr', '2.79*eta(T)');
model.component('comp1').material('mat1').propertyGroup('def').func('an3').set('args', {'T'});
model.component('comp1').material('mat1').propertyGroup('def').func('an3').set('fununit', 'Pa*s');
model.component('comp1').material('mat1').propertyGroup('def').func('an3').set('argunit', {'K'});
model.component('comp1').material('mat1').propertyGroup('def').func('an3').set('plotargs', {'T' '273.15' '553.75'});
model.component('comp1').material('mat1').propertyGroup('def').set('thermalexpansioncoefficient', '');
model.component('comp1').material('mat1').propertyGroup('def').set('bulkviscosity', '');
model.component('comp1').material('mat1').propertyGroup('def').set('thermalexpansioncoefficient', {'alpha_p(T)' '0' '0' '0' 'alpha_p(T)' '0' '0' '0' 'alpha_p(T)'});
model.component('comp1').material('mat1').propertyGroup('def').set('bulkviscosity', 'muB(T)');
model.component('comp1').material('mat1').propertyGroup('def').set('dynamicviscosity', 'dynamic_viscosity');
model.component('comp1').material('mat1').propertyGroup('def').set('ratioofspecificheat', 'gamma_w(T)');
model.component('comp1').material('mat1').propertyGroup('def').set('electricconductivity', {'5.5e-6[S/m]' '0' '0' '0' '5.5e-6[S/m]' '0' '0' '0' '5.5e-6[S/m]'});
model.component('comp1').material('mat1').propertyGroup('def').set('heatcapacity', 'Cp(T)');
model.component('comp1').material('mat1').propertyGroup('def').set('density', 'density');
model.component('comp1').material('mat1').propertyGroup('def').set('thermalconductivity', {'k(T)' '0' '0' '0' 'k(T)' '0' '0' '0' 'k(T)'});
model.component('comp1').material('mat1').propertyGroup('def').set('soundspeed', 'speed_of_sound');
model.component('comp1').material('mat1').propertyGroup('def').set('compressibility', 'comp_fluid');
model.component('comp1').material('mat1').propertyGroup('def').addInput('temperature');
model.component('comp1').material('pmat1').set('porosity', 'porosity_pm');
model.component('comp1').material('pmat1').propertyGroup('def').set('hydraulicpermeability', {'permeability_pm' '0' '0' '0' 'permeability_pm' '0' '0' '0' 'permeability_pm'});
model.component('comp1').material('pmat1').feature('fluid1').set('link', 'mat1');

model.component('comp1').physics('dl2').label('Darcy''s LawSteady');
model.component('comp1').physics('dl2').prop('PhysicalModelProperty').set('pref', '0[atm]');
model.component('comp1').physics('dl2').feature('porous1').set('storageModelType', 'poroelastic');
model.component('comp1').physics('dl2').feature('porous1').set('Sp', '1e-9');
model.component('comp1').physics('dl2').feature('porous1').feature('pm1').set('epsilon', 0.25);
model.component('comp1').physics('dl2').feature('porous1').feature('pm1').set('kappa', {'4.93e-14[m^2]'; '0'; '0'; '0'; '4.93e-14[m^2]'; '0'; '0'; '0'; '4.93e-14[m^2]'});
model.component('comp1').physics('dl2').feature('pr1').set('p0', 'pressure_reservoir_boundary');
model.component('comp1').physics('dl2').feature('ms1').set('Qm', '-u0*(pipe_R^2*pi)*density/4/0.093643[m^3]');
model.component('comp1').physics('dl2').feature('ms1').label('Mass Source 1  -u0*(pipe_R^2*pi)*density/4/(porous_domain_thickness*pi*rw^2)/4');
model.component('comp1').physics('pfl').label('Pipe Flow Steady');
model.component('comp1').physics('pfl').feature('fp1').set('rho', '700[kg/m^3]');
model.component('comp1').physics('pfl').feature('fp1').set('minput_temperature_src', 'fromCommonDef');
model.component('comp1').physics('pfl').feature('pipe1').set('shape', 'Round');
model.component('comp1').physics('pfl').feature('pipe1').set('innerd', '2*pipe_R');
model.component('comp1').physics('pfl').feature('pipe1').set('frictionmodel', 100);
model.component('comp1').physics('pfl').feature('pipe1').set('roughness', 14);
model.component('comp1').physics('pfl').feature('pipe1').set('f', 'friction_factor');
model.component('comp1').physics('pfl').feature('pr1').set('p0', 'p_pipe_boundary_steady');
model.component('comp1').physics('pfl').feature('pr1').label('Pressure 1  ');
model.component('comp1').physics('pfl').feature('init1').set('p4', '(p0+density*9.81[m/s^2]*(-z))');
model.component('comp1').physics('pfl').feature('init1').set('u2', '-u0');
model.component('comp1').physics('pfl').feature('vf1').set('F3D', {'0'; '0'; '(-g_const)*density'});
model.component('comp1').physics('pfl').feature('out1').set('spec', 0);
model.component('comp1').physics('pfl').feature('out1').set('u0', 'u0');
model.component('comp1').physics('dl').prop('PhysicalModelProperty').set('pref', '0[atm]');
model.component('comp1').physics('dl').feature('porous1').set('storageModelType', 'poroelastic');
model.component('comp1').physics('dl').feature('porous1').set('Sp', '1e-9');
model.component('comp1').physics('dl').feature('porous1').feature('fluid1').set('rho', '700[kg/m^3]');
model.component('comp1').physics('dl').feature('porous1').feature('fluid1').set('chif', '1.5e-5[1/psi]');
model.component('comp1').physics('dl').feature('porous1').feature('pm1').set('epsilon', 0.25);
model.component('comp1').physics('dl').feature('porous1').feature('pm1').set('kappa', {'4.93e-14[m^2]'; '0'; '0'; '0'; '4.93e-14[m^2]'; '0'; '0'; '0'; '4.93e-14[m^2]'});
model.component('comp1').physics('dl').feature('init1').set('p', 'p3');
model.component('comp1').physics('dl').feature('pr1').set('p0', 'pressure_reservoir_boundary');
model.component('comp1').physics('dl').feature('ms1').set('Qm', 'u_pipe_boundary*(pipe_R^2*pi)*density/4/0.093643[m^3]');
model.component('comp1').physics('dl').feature('ms1').label('Mass Source 1 u_pipe_boundary*(pipe_R^2*pi)*density/4/(porous_domain_thickness*pi*rw^2)/4');
model.component('comp1').physics('whtd').feature('fp1').set('rho', '700[kg/m^3]');
model.component('comp1').physics('whtd').feature('fp1').set('cs', '1000[m/s]');
model.component('comp1').physics('whtd').feature('fp1').set('minput_temperature_src', 'fromCommonDef');
model.component('comp1').physics('whtd').feature('pipe1').set('frictionmodel', 100);
model.component('comp1').physics('whtd').feature('pipe1').set('f', 'friction_factor');
model.component('comp1').physics('whtd').feature('pipe1').set('shape', 'Round');
model.component('comp1').physics('whtd').feature('pipe1').set('innerd', '2*pipe_R');
model.component('comp1').physics('whtd').feature('pipe1').set('dw', 'w');
model.component('comp1').physics('whtd').feature('pipe1').set('E_mat', 'userdef');
model.component('comp1').physics('whtd').feature('pipe1').set('E', 'E');
model.component('comp1').physics('whtd').feature('init1').set('p', 'p4');
model.component('comp1').physics('whtd').feature('init1').set('u', '-u0');
model.component('comp1').physics('whtd').feature('pres1').set('p', 'nojac(p_pipe_boundary)');
model.component('comp1').physics('whtd').feature('pres1').label('Pressure 1 ');
model.component('comp1').physics('whtd').feature('source1').set('uin', '-u0*(1-comp1.rm1(t/(1e-1 [s])))');
model.component('comp1').physics('whtd').feature('source1').label('Velocity 1  ');
model.component('comp1').physics('whtd').feature('vf1').set('F3D', {'0'; '0'; '(-g_const)*density'});

model.component('comp1').mesh('mesh1').feature('size').set('hauto', 1);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').active(false);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('hauto', 4);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('hmax', 0.1);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('hmin', 0.1);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('hgrad', 1.3);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('dis1').set('type', 'predefined');
model.component('comp1').mesh('mesh1').feature('ftet1').feature('dis1').set('elemcount', 'N');
model.component('comp1').mesh('mesh1').run;

model.component('comp1').probe('point1').set('probename', 'u_pipe_boundary');
model.component('comp1').probe('point1').set('expr', 'u');
model.component('comp1').probe('point1').set('unit', 'm/s');
model.component('comp1').probe('point1').set('descr', 'Tangential velocity');
model.component('comp1').probe('point1').set('table', 'tbl1');
model.component('comp1').probe('point1').set('window', 'window1');
model.component('comp1').probe('dom1').set('probename', 'p_pipe_boundary_steady');
model.component('comp1').probe('dom1').set('table', 'tbl1');
model.component('comp1').probe('dom1').set('window', 'window1');
model.component('comp1').probe('dom2').set('probename', 'p_pipe_boundary');
model.component('comp1').probe('dom2').set('expr', 'p2');
model.component('comp1').probe('dom2').set('table', 'tbl1');
model.component('comp1').probe('dom2').set('window', 'window1');

model.study.create('std6');
model.study('std6').create('stat', 'Stationary');
model.study('std6').create('time', 'Transient');
model.study('std6').feature('stat').set('useadvanceddisable', true);
model.study('std6').feature('stat').set('disabledphysics', {'dl'});
model.study('std6').feature('stat').set('activate', {'dl2' 'on' 'pfl' 'on' 'dl' 'off' 'whtd' 'off' 'frame:spatial1' 'on'  ...
'frame:material1' 'on'});
model.study('std6').feature('time').set('useadvanceddisable', true);
model.study('std6').feature('time').set('activate', {'dl2' 'off' 'pfl' 'off' 'dl' 'on' 'whtd' 'on' 'frame:spatial1' 'on'  ...
'frame:material1' 'on'});

model.sol.create('sol12');
model.sol('sol12').study('std6');
model.sol('sol12').attach('std6');
model.sol('sol12').create('st1', 'StudyStep');
model.sol('sol12').create('v1', 'Variables');
model.sol('sol12').create('s1', 'Stationary');
model.sol('sol12').create('su1', 'StoreSolution');
model.sol('sol12').create('st2', 'StudyStep');
model.sol('sol12').create('v2', 'Variables');
model.sol('sol12').create('t1', 'Time');
model.sol('sol12').feature('s1').create('se1', 'Segregated');
model.sol('sol12').feature('s1').create('d1', 'Direct');
model.sol('sol12').feature('s1').create('i1', 'Iterative');
model.sol('sol12').feature('s1').feature('se1').create('ss1', 'SegregatedStep');
model.sol('sol12').feature('s1').feature('se1').create('ss2', 'SegregatedStep');
model.sol('sol12').feature('s1').feature('se1').feature.remove('ssDef');
model.sol('sol12').feature('s1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('pr').create('sl1', 'SORLine');
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('po').create('sl1', 'SORLine');
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol12').feature('s1').feature.remove('fcDef');
model.sol('sol12').feature('t1').create('se1', 'Segregated');
model.sol('sol12').feature('t1').feature('se1').create('ss1', 'SegregatedStep');
model.sol('sol12').feature('t1').feature('se1').create('ss2', 'SegregatedStep');
model.sol('sol12').feature('t1').feature('se1').feature.remove('ssDef');
model.sol('sol12').feature('t1').feature.remove('fcDef');

model.result.dataset.create('dset9', 'Solution');
model.result.dataset.create('avh1', 'Average');
model.result.dataset.create('dset10', 'Solution');
model.result.dataset.create('dset11', 'Solution');
model.result.dataset.create('cln1', 'CutLine3D');
model.result.dataset.create('rm1_ds1', 'Grid1D');
model.result.dataset.create('avh2', 'Average');
model.result.dataset.create('avh3', 'Average');
model.result.dataset('dset9').set('probetag', 'dom2');
model.result.dataset('avh1').set('probetag', 'point1');
model.result.dataset('avh1').set('data', 'dset9');
model.result.dataset('avh1').selection.geom('geom1', 0);
model.result.dataset('avh1').selection.set([2]);
model.result.dataset('dset11').set('solution', 'sol13');
model.result.dataset('cln1').set('data', 'dset10');
model.result.dataset('rm1_ds1').set('data', 'none');
model.result.dataset('avh2').set('probetag', 'dom1');
model.result.dataset('avh2').set('data', 'dset9');
model.result.dataset('avh2').selection.geom('geom1', 3);
model.result.dataset('avh2').selection.set([1]);
model.result.dataset('avh3').set('probetag', 'dom2');
model.result.dataset('avh3').set('data', 'dset9');
model.result.dataset('avh3').selection.geom('geom1', 3);
model.result.dataset('avh3').selection.set([1]);
model.result.dataset.remove('dset1');
model.result.dataset.remove('dset2');
model.result.numerical.create('pev1', 'EvalPoint');
model.result.numerical.create('pev2', 'EvalPoint');
model.result.numerical.create('pev3', 'EvalPoint');
model.result.numerical('pev1').set('probetag', 'point1');
model.result.numerical('pev2').set('probetag', 'dom1');
model.result.numerical('pev3').set('probetag', 'dom2');
model.result.create('pg14', 'PlotGroup1D');
model.result.create('pg15', 'PlotGroup3D');
model.result.create('pg25', 'PlotGroup1D');
model.result.create('pg21', 'PlotGroup1D');
model.result.create('pg17', 'PlotGroup1D');
model.result.create('pg23', 'PlotGroup1D');
model.result.create('pg24', 'PlotGroup1D');
model.result('pg14').set('probetag', 'window1_default');
model.result('pg14').create('tblp1', 'Table');
model.result('pg14').feature('tblp1').set('probetag', 'point1,point2,point3,bnd1,bnd2,dom1,dom2');
model.result('pg15').set('data', 'dset10');
model.result('pg15').create('str1', 'Streamline');
model.result('pg15').create('vol1', 'Volume');
model.result('pg15').feature('str1').selection.set([1 2 3 4 5 7 8 10]);
model.result('pg15').feature('str1').create('col1', 'Color');
model.result('pg15').feature('str1').feature('col1').set('expr', 'dl2.U');
model.result('pg25').set('data', 'dset10');
model.result('pg25').create('lngr1', 'LineGraph');
model.result('pg25').feature('lngr1').set('xdata', 'expr');
model.result('pg25').feature('lngr1').selection.set([6 17]);
model.result('pg21').set('data', 'dset10');
model.result('pg21').create('lngr1', 'LineGraph');
model.result('pg21').create('lngr2', 'LineGraph');
model.result('pg21').feature('lngr1').set('xdata', 'expr');
model.result('pg21').feature('lngr1').selection.set([4]);
model.result('pg21').feature('lngr1').set('expr', 'p4');
model.result('pg21').feature('lngr2').set('xdata', 'expr');
model.result('pg21').feature('lngr2').selection.set([4]);
model.result('pg21').feature('lngr2').set('expr', 'u2');
model.result('pg17').set('data', 'dset10');
model.result('pg17').create('lngr1', 'LineGraph');
model.result('pg17').create('lngr2', 'LineGraph');
model.result('pg17').create('ptgr1', 'PointGraph');
model.result('pg17').create('ptgr2', 'PointGraph');
model.result('pg17').feature('lngr1').set('xdata', 'expr');
model.result('pg17').feature('lngr1').selection.set([4]);
model.result('pg17').feature('lngr1').set('expr', 'p');
model.result('pg17').feature('lngr2').set('xdata', 'expr');
model.result('pg17').feature('lngr2').selection.set([4]);
model.result('pg17').feature('lngr2').set('expr', 'u');
model.result('pg17').feature('ptgr1').selection.set([3]);
model.result('pg17').feature('ptgr1').set('expr', 'p');
model.result('pg17').feature('ptgr2').selection.set([2]);
model.result('pg17').feature('ptgr2').set('expr', 'p');
model.result('pg23').set('data', 'dset10');
model.result('pg23').create('lngr1', 'LineGraph');
model.result('pg23').create('lngr2', 'LineGraph');
model.result('pg23').feature('lngr1').set('xdata', 'expr');
model.result('pg23').feature('lngr1').selection.set([17]);
model.result('pg23').feature('lngr1').set('expr', 'p2');
model.result('pg23').feature('lngr2').set('data', 'dset10');
model.result('pg23').feature('lngr2').set('xdata', 'expr');
model.result('pg23').feature('lngr2').selection.set([17]);
model.result('pg23').feature('lngr2').set('expr', 'p2');
model.result('pg24').create('plot1', 'Function');
model.result('pg24').feature('plot1').set('expr', '-u0*(1-comp1.rm1(t/(1e-1 [s])))');

model.component('comp1').probe('point1').genResult([]);
model.component('comp1').probe('dom1').genResult([]);
model.component('comp1').probe('dom2').genResult([]);

model.study('std6').feature('time').set('tlist', 'range(0,dt_out,15)');
model.study('std6').feature('time').set('useinitsol', true);
model.study('std6').feature('time').set('initstudy', 'std6');
model.study('std6').feature('time').set('solnum', 'auto');

model.sol('sol12').attach('std6');
model.sol('sol12').feature('st1').label('Compile Equations: Stationary');
model.sol('sol12').feature('v1').label('Dependent Variables 1.1');
model.sol('sol12').feature('v1').set('clist', {'0.015[s]'});
model.sol('sol12').feature('s1').label('Stationary Solver 1.1');
model.sol('sol12').feature('s1').feature('dDef').label('Direct 2');
model.sol('sol12').feature('s1').feature('aDef').label('Advanced 1');
model.sol('sol12').feature('s1').feature('aDef').set('cachepattern', true);
model.sol('sol12').feature('s1').feature('se1').label('Segregated 1.1');
model.sol('sol12').feature('s1').feature('se1').feature('ss1').label('Pressure p3');
model.sol('sol12').feature('s1').feature('se1').feature('ss1').set('segvar', {'comp1_p3'});
model.sol('sol12').feature('s1').feature('se1').feature('ss1').set('linsolver', 'd1');
model.sol('sol12').feature('s1').feature('se1').feature('ss2').label('Pipe Flow Steady');
model.sol('sol12').feature('s1').feature('se1').feature('ss2').set('segvar', {'comp1_p4' 'comp1_u2'});
model.sol('sol12').feature('s1').feature('d1').label('Direct, pressure (dl2)');
model.sol('sol12').feature('s1').feature('d1').set('linsolver', 'pardiso');
model.sol('sol12').feature('s1').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol12').feature('s1').feature('i1').label('AMG, pressure (dl2)');
model.sol('sol12').feature('s1').feature('i1').set('nlinnormuse', true);
model.sol('sol12').feature('s1').feature('i1').set('maxlinit', 50);
model.sol('sol12').feature('s1').feature('i1').feature('ilDef').label('Incomplete LU 1');
model.sol('sol12').feature('s1').feature('i1').feature('mg1').label('Multigrid 1.1');
model.sol('sol12').feature('s1').feature('i1').feature('mg1').set('prefun', 'saamg');
model.sol('sol12').feature('s1').feature('i1').feature('mg1').set('maxcoarsedof', 50000);
model.sol('sol12').feature('s1').feature('i1').feature('mg1').set('usesmooth', false);
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('pr').label('Presmoother 1');
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('pr').feature('soDef').label('SOR 1');
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sl1').label('SOR Line 1.1');
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('linesweeptype', 'ssor');
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('iter', 1);
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('linerelax', 0.7);
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('relax', 0.5);
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('po').label('Postsmoother 1');
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('po').feature('soDef').label('SOR 1');
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('po').feature('sl1').label('SOR Line 1.1');
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('po').feature('sl1').set('linesweeptype', 'ssor');
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('po').feature('sl1').set('iter', 1);
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('po').feature('sl1').set('linerelax', 0.7);
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('po').feature('sl1').set('relax', 0.5);
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('cs').label('Coarse Solver 1');
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('cs').feature('dDef').label('Direct 2');
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('cs').feature('d1').label('Direct 1.1');
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol12').feature('s1').feature('i1').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol12').feature('su1').label('Solution Store 1.1');
model.sol('sol12').feature('st2').label('Compile Equations: Time Dependent');
model.sol('sol12').feature('st2').set('studystep', 'time');
model.sol('sol12').feature('v2').label('Dependent Variables 2.1');
model.sol('sol12').feature('v2').set('initsol', 'sol12');
model.sol('sol12').feature('v2').set('solnum', 'auto');
model.sol('sol12').feature('v2').set('resscalemethod', 'manual');
model.sol('sol12').feature('v2').set('notsolmethod', 'sol');
model.sol('sol12').feature('v2').set('notsol', 'sol12');
model.sol('sol12').feature('v2').set('notsoluse', 'sol13');
model.sol('sol12').feature('v2').set('notsolnum', 'auto');
model.sol('sol12').feature('v2').set('clist', {'range(0,dt_out,15)' '0.015[s]'});
model.sol('sol12').feature('t1').label('Time-Dependent Solver 1.1');
model.sol('sol12').feature('t1').set('control', 'time');
model.sol('sol12').feature('t1').set('tlist', 'range(0,dt_out,15)');
model.sol('sol12').feature('t1').set('tout', 'tstepsclosest');
model.sol('sol12').feature('t1').set('rtol', 1.0E-4);
model.sol('sol12').feature('t1').set('maxstepconstraintbdf', 'const');
model.sol('sol12').feature('t1').set('maxstepbdf', 'dt_max');
model.sol('sol12').feature('t1').feature('dDef').label('Direct 1');
model.sol('sol12').feature('t1').feature('aDef').label('Advanced 1');
model.sol('sol12').feature('t1').feature('se1').label('Segregated 1.1');
model.sol('sol12').feature('t1').feature('se1').feature('ss1').label('Darcy''s Law');
model.sol('sol12').feature('t1').feature('se1').feature('ss1').set('segvar', {'comp1_p2'});
model.sol('sol12').feature('t1').feature('se1').feature('ss2').label('Water Hammer');
model.sol('sol12').feature('t1').feature('se1').feature('ss2').set('segvar', {'comp1_p' 'comp1_u'});
model.sol('sol12').feature('t1').feature('se1').feature.remove('whtd1');
model.sol('sol12').feature('t1').feature('se1').feature.remove('dl1');
model.sol('sol12').runAll;

model.result.dataset('dset9').label('Probe Solution 9');
model.result.dataset('cln1').active(false);
model.result.dataset('cln1').set('method', 'pointdir');
model.result.dataset('cln1').set('pdpoint', {'rw_not_used' '0' '-506'});
model.result.dataset('rm1_ds1').set('function', 'rm1');
model.result.dataset('rm1_ds1').set('par1', 't');
model.result.dataset('rm1_ds1').set('parmax1', 10);
model.result.dataset('rm1_ds1').set('res1', 10000);
model.result.evaluationGroup('eg1').set('data', 'dset10');
model.result.evaluationGroup('eg1').set('looplevelinput', {'all'});
model.result.evaluationGroup('eg1').feature('pev1').set('expr', {'p3'});
model.result.evaluationGroup('eg1').feature('pev1').set('unit', {'Pa'});
model.result.evaluationGroup('eg1').feature('pev1').set('descr', {'Pressure'});
model.result.evaluationGroup('eg1').feature('pev1').selection.set([2]);
model.result.evaluationGroup('eg1').run;
model.result('pg14').label('Probe Plot Group 14');
model.result('pg14').set('xlabel', 'Time (s)');
model.result('pg14').set('windowtitle', 'Probe Plot 1');
model.result('pg14').set('xlabelactive', false);
model.result('pg14').feature('tblp1').label('Probe Table Graph 1');
model.result('pg14').feature('tblp1').set('table', 'tbl1');
model.result('pg14').feature('tblp1').set('plotcolumninput', 'manual');
model.result('pg14').feature('tblp1').set('legend', true);
model.result('pg14').feature.remove('tblp2');
model.result('pg15').label('InitialCond_Reservoir (dl2)');
model.result('pg15').set('titletype', 'custom');
model.result('pg15').feature('str1').set('posmethod', 'start');
model.result('pg15').feature('str1').set('pointtype', 'arrow');
model.result('pg15').feature('str1').set('arrowcount', 71);
model.result('pg15').feature('str1').set('arrowlength', 'logarithmic');
model.result('pg15').feature('str1').set('arrowscale', 94910.24732807002);
model.result('pg15').feature('str1').set('smooth', 'internal');
model.result('pg15').feature('str1').set('arrowcountactive', false);
model.result('pg15').feature('str1').set('arrowscaleactive', false);
model.result('pg15').feature('str1').set('resolution', 'normal');
model.result('pg15').feature('vol1').label('Pressure');
model.result('pg15').feature('vol1').set('resolution', 'normal');
model.result('pg25').label('InitialCond_Porous_Media');
model.result('pg25').set('looplevelinput', {'first'});
model.result('pg25').set('xlabel', 'x-coordinate (m)');
model.result('pg25').set('ylabel', 'Pressure (Pa)');
model.result('pg25').set('axislimits', true);
model.result('pg25').set('xmin', 'rw');
model.result('pg25').set('xmax', 16.28093397681022);
model.result('pg25').set('ymin', 1.3410677470548363E7);
model.result('pg25').set('ymax', 1.380739825702433E7);
model.result('pg25').set('xlog', true);
model.result('pg25').set('xlabelactive', false);
model.result('pg25').set('ylabelactive', false);
model.result('pg25').feature('lngr1').label('pressure');
model.result('pg25').feature('lngr1').set('xdataexpr', 'x');
model.result('pg25').feature('lngr1').set('xdataunit', 'm');
model.result('pg25').feature('lngr1').set('xdatadescr', 'x-coordinate');
model.result('pg25').feature('lngr1').set('legend', true);
model.result('pg25').feature('lngr1').set('legendprefix', 'pressure');
model.result('pg25').feature('lngr1').set('smooth', 'none');
model.result('pg25').feature('lngr1').set('resolution', 'normal');
model.result('pg21').label('InitialCond_Pipe');
model.result('pg21').set('xlabel', 'z-coordinate (m)');
model.result('pg21').set('ylabel', 'Pressure (Pa)');
model.result('pg21').set('yseclabel', 'Tangential velocity (m/s)');
model.result('pg21').set('twoyaxes', true);
model.result('pg21').set('plotonsecyaxis', {'pressure' 'off' 'lngr1'; 'velocity' 'on' 'lngr2'});
model.result('pg21').set('xlabelactive', false);
model.result('pg21').set('ylabelactive', false);
model.result('pg21').set('yseclabelactive', false);
model.result('pg21').feature('lngr1').label('pressure');
model.result('pg21').feature('lngr1').set('xdataexpr', 'z');
model.result('pg21').feature('lngr1').set('xdataunit', 'm');
model.result('pg21').feature('lngr1').set('xdatadescr', 'z-coordinate');
model.result('pg21').feature('lngr1').set('legend', true);
model.result('pg21').feature('lngr1').set('legendprefix', 'pressure');
model.result('pg21').feature('lngr1').set('resolution', 'normal');
model.result('pg21').feature('lngr2').label('velocity');
model.result('pg21').feature('lngr2').set('xdataexpr', 'z');
model.result('pg21').feature('lngr2').set('xdataunit', 'm');
model.result('pg21').feature('lngr2').set('xdatadescr', 'z-coordinate');
model.result('pg21').feature('lngr2').set('legend', true);
model.result('pg21').feature('lngr2').set('legendprefix', 'pressure');
model.result('pg21').feature('lngr2').set('resolution', 'normal');
model.result('pg17').label('PipeTransient');
model.result('pg17').set('xlabel', 'Time (s)');
model.result('pg17').set('ylabel', 'Pressure (bar)');
model.result('pg17').set('yseclabel', 'Pressure (bar)');
model.result('pg17').set('twoyaxes', true);
model.result('pg17').set('plotonsecyaxis', {'pressure' 'off' 'lngr1';  ...
'velocity' 'off' 'lngr2';  ...
'Point Graph 1' 'off' 'ptgr1';  ...
'Point Graph 2' 'on' 'ptgr2'});
model.result('pg17').set('axislimits', true);
model.result('pg17').set('xmin', -0.26826299709381757);
model.result('pg17').set('xmax', 15.268262997093817);
model.result('pg17').set('ymin', 99.5);
model.result('pg17').set('ymax', 105);
model.result('pg17').set('yminsec', 131.5);
model.result('pg17').set('ymaxsec', 137);
model.result('pg17').set('manualgrid', true);
model.result('pg17').set('xspacing', 2);
model.result('pg17').set('yspacing', 0.5);
model.result('pg17').set('ysecspacing', '.5');
model.result('pg17').set('showlegends', false);
model.result('pg17').set('xlabelactive', false);
model.result('pg17').set('ylabelactive', false);
model.result('pg17').set('yseclabelactive', false);
model.result('pg17').feature('lngr1').active(false);
model.result('pg17').feature('lngr1').label('pressure');
model.result('pg17').feature('lngr1').set('xdataexpr', 'z');
model.result('pg17').feature('lngr1').set('xdataunit', 'm');
model.result('pg17').feature('lngr1').set('xdatadescr', 'z-coordinate');
model.result('pg17').feature('lngr1').set('legend', true);
model.result('pg17').feature('lngr1').set('resolution', 'normal');
model.result('pg17').feature('lngr2').active(false);
model.result('pg17').feature('lngr2').label('velocity');
model.result('pg17').feature('lngr2').set('xdataexpr', 'z');
model.result('pg17').feature('lngr2').set('xdataunit', 'm');
model.result('pg17').feature('lngr2').set('xdatadescr', 'z-coordinate');
model.result('pg17').feature('lngr2').set('legend', true);
model.result('pg17').feature('lngr2').set('resolution', 'normal');
model.result('pg17').feature('ptgr1').set('unit', 'bar');
model.result('pg17').feature('ptgr1').set('linecolor', 'custom');
model.result('pg17').feature('ptgr1').set('customlinecolor', [0.9490196108818054 0.3960784375667572 0.13333334028720856]);
model.result('pg17').feature('ptgr1').set('linewidth', 3);
model.result('pg17').feature('ptgr1').set('legend', true);
model.result('pg17').feature('ptgr2').set('unit', 'bar');
model.result('pg17').feature('ptgr2').set('linecolor', 'custom');
model.result('pg17').feature('ptgr2').set('customlinecolor', [0 0.3333333432674408 0.5882353186607361]);
model.result('pg17').feature('ptgr2').set('linewidth', 3);
model.result('pg17').feature('ptgr2').set('legend', true);
model.result('pg23').label('Porous_Media_Transient');
model.result('pg23').set('looplevelinput', {'interp'});
model.result('pg23').set('interp', {'range(0,1,15)'});
model.result('pg23').set('xlabel', 'x-coordinate (m)');
model.result('pg23').set('ylabel', 'Pressure (Pa)');
model.result('pg23').set('axislimits', true);
model.result('pg23').set('xmin', 'rw');
model.result('pg23').set('xmax', 16.16894555222339);
model.result('pg23').set('ymin', 1.3452743760227429E7);
model.result('pg23').set('ymax', 1.3806683544678375E7);
model.result('pg23').set('xlog', true);
model.result('pg23').set('xlabelactive', false);
model.result('pg23').set('ylabelactive', false);
model.result('pg23').feature('lngr1').set('xdataexpr', 'x');
model.result('pg23').feature('lngr1').set('xdataunit', 'm');
model.result('pg23').feature('lngr1').set('xdatadescr', 'x-coordinate');
model.result('pg23').feature('lngr1').set('linecolor', 'custom');
model.result('pg23').feature('lngr1').set('customlinecolor', [0.9490196108818054 0.3960784375667572 0.13333334028720856]);
model.result('pg23').feature('lngr1').set('linewidth', 2);
model.result('pg23').feature('lngr1').set('smooth', 'internal');
model.result('pg23').feature('lngr1').set('resolution', 'normal');
model.result('pg23').feature('lngr2').set('looplevelinput', {'interp'});
model.result('pg23').feature('lngr2').set('interp', {'0,15'});
model.result('pg23').feature('lngr2').set('xdataexpr', 'x');
model.result('pg23').feature('lngr2').set('xdataunit', 'm');
model.result('pg23').feature('lngr2').set('xdatadescr', 'x-coordinate');
model.result('pg23').feature('lngr2').set('linecolor', 'custom');
model.result('pg23').feature('lngr2').set('linewidth', 3);
model.result('pg23').feature('lngr2').set('smooth', 'internal');
model.result('pg23').feature('lngr2').set('resolution', 'normal');
model.result('pg24').label('Vane_Closing_velocity');
model.result('pg24').set('data', 'rm1_ds1');
model.result('pg24').set('solrepresentation', 'solnum');
model.result('pg24').set('titletype', 'manual');
model.result('pg24').set('title', 'rm1');
model.result('pg24').set('ylabelactive', true);
model.result('pg24').set('axislimits', true);
model.result('pg24').set('xmin', -0.017700588956533453);
model.result('pg24').set('xmax', 1.0168004989475325);
model.result('pg24').set('ymin', -0.1009450953084481);
model.result('pg24').set('ymax', 0.0018332589732020694);
model.result('pg24').feature('plot1').set('solrepresentation', 'solnum');
model.result('pg24').feature('plot1').set('unit', '');
model.result('pg24').feature('plot1').set('xdataexpr', 't');
model.result('pg24').feature('plot1').set('xdataunit', 'm');
model.result('pg24').feature('plot1').set('xdatadescractive', true);
model.result('pg24').feature('plot1').set('xdatadescr', '');

out = model;
